import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import BackgroundWithTorus from "./components/BackgroundWithTorus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Handmade ceramics and pottery. Contact us for custom orders or questions." />
        <meta property="og:title" content="Misfitz Pottery | Handmade Pottery & Ceramics" />
        <meta property="og:description" content="Handmade ceramics and pottery. Contact us for custom orders or questions." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://misfitzpottery.com/" />
        <meta property="og:image" content="/images/misfitzlogo.png" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Misfitz Pottery | Handmade Pottery & Ceramics" />
        <meta name="twitter:description" content="Handmade ceramics and pottery. Contact us for custom orders or questions." />
        <meta name="twitter:image" content="/images/misfitzlogo.png" />
        <link rel="canonical" href="https://misfitzpottery.com/" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
        <BackgroundWithTorus />
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
